"""add gender in User

Revision ID: 0feeeaa9081f
Revises: 04b334c9c547
Create Date: 2019-03-19 22:39:42.315183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0feeeaa9081f'
down_revision = '04b334c9c547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
