"""add avatar

Revision ID: f234abdd5f8a
Revises: 0feeeaa9081f
Create Date: 2019-03-19 23:02:30.978610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f234abdd5f8a'
down_revision = '0feeeaa9081f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_avatar'), 'user', ['avatar'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_avatar'), table_name='user')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
